dist: trusty

language: cpp

compiler:
 - gcc

before_install:
 - git clone http://github.com/FantasticOnAStick/foas_common.git
 - cd foas_common && ./prepare.sh
 - cd -
 - git clone http://github.com/FantasticOnAStick/foas_message.git
 - git clone http://github.com/FantasticOnAStick/foas_plugin.git

script:
 - cd foas_plugin
 - mkdir build
 - cd build
 - cmake ..
 - make
 - ctest --verbose